import React from "react";
import type { Metadata } from "next";
import { Geist_Mono, Inter, Inter_Tight } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-family-sans",
  subsets: ["latin"],
});

const interTight = Inter_Tight({
  variable: "--font-family-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-family-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interSans.variable} ${interTight.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
